export const SET_ENTITY = "SET_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";
export const UPDATE_ENTITY = "UPDATE_ENTITY";
export const DELETE_ENTITY = "DELETE_ENTITY";

export const UPDATE_PIZZA = "UPDATE_PIZZA";
export const UPDATE_PIZZA_INGREDIENT = "UPDATE_PIZZA_INGREDIENT";
export const RESET_PIZZA = "RESET_PIZZA";

export const SET_CART_ITEM_COUNT = "SET_CART_ITEM_COUNT";
export const SET_CART_ITEM_PIZZA = "SET_CART_ITEM_PIZZA";
export const SET_CART_DELIVERY_METHOD = "SET_CART_DELIVERY_METHOD";
export const SET_CART_PHONE = "SET_CART_PHONE";
export const SET_CART_ADDRESS = "SET_CART_ADDRESS";
export const RESET_CART_ADDRESS = "RESET_CART_ADDRESS";
export const RESET_CART = "RESET_CART";
